#ifndef __AUDIO_API_DEBUG__
#define __AUDIO_API_DEBUG__

#include <global.h>

typedef enum {
    AUDIOAPI_DEBUG_EVENT_QUEUE_EXT_CMD = 1,
    AUDIOAPI_DEBUG_EVENT_PROCESS_SEQ_CMD = 2,
    AUDIOAPI_DEBUG_EVENT_START_SEQUENCE = 3,
    AUDIOAPI_DEBUG_EVENT_STOP_SEQUENCE = 4,
    AUDIOAPI_DEBUG_EVENT_PLAY_SCENE_SEQUENCE = 5,
    AUDIOAPI_DEBUG_EVENT_PLAY_SUB_BGM = 6,
    AUDIOAPI_DEBUG_EVENT_PLAY_FANFARE = 7,
    AUDIOAPI_DEBUG_EVENT_PLAY_OBJ_BGM = 8,
    AUDIOAPI_DEBUG_EVENT_PLAY_CUTSCENE_SEQUENCE = 9,
    AUDIOAPI_DEBUG_EVENT_START_MORNING_SEQUENCE = 10,
    AUDIOAPI_DEBUG_EVENT_BGM_BLEND_INTENT = 11,
    AUDIOAPI_DEBUG_EVENT_SEQ_IO_CHANGE = 12,
    AUDIOAPI_DEBUG_EVENT_MUTE_ALL_EXCEPT_SYS_OCA = 13,
    AUDIOAPI_DEBUG_EVENT_SET_SFX_VOL_EXCEPT = 14,
    AUDIOAPI_DEBUG_EVENT_SFX_VOL_TRANSITION = 15,
    AUDIOAPI_DEBUG_EVENT_MUTE_SFX_AMBIENCE_ONLY = 16,
    AUDIOAPI_DEBUG_EVENT_START_SFX_PLAYER = 17,
    AUDIOAPI_DEBUG_EVENT_MUTE_SFX_AMBIENCE_SYS_OCA = 18,
    AUDIOAPI_DEBUG_EVENT_SET_SPEC = 19,
    AUDIOAPI_DEBUG_EVENT_RESET_HEAP_STEP3 = 20,
    AUDIOAPI_DEBUG_EVENT_SFX_MUTE_BANKS_BEFORE = 21,
    AUDIOAPI_DEBUG_EVENT_SFX_MUTE_BANKS_AFTER = 22,
    AUDIOAPI_DEBUG_EVENT_SFX_BANK_MASK = 23,
} AudioApiDebugEventTag;

extern u8 gAudioApiDebugHttpEnabled;
extern u8 gAudioApiDebugVerbose;

void AudioApi_DebugInitFromConfig(void);
void AudioApi_DebugSyncSnapshot(void);
void AudioApi_DebugEvent(u32 tag, s32 a, s32 b, s32 c, s32 d);

#endif
